### ISSUE TITLE
Error: Couldn't find 'visualization.json' in visualization bundle

### ISSUE THREAD

**Issue by zhuohanl** [Zoomdata/custom-regions-visualization#3]
Hi,

I tried to follow your Home.md step by step but met the following error after running the command:
` zd-chart add -a <http[s]://<serveraddress>:<port>/<zoomdata> -u <username>:<password> "<chart name>" <filename.zip>`

The error:
`message: 400 - "{\"details\":\"Couldn't find 'visualization.json' in visualization bundle.\",\"error\":\"INTERNAL_ERROR\"}"`
`stack:`
`  - StatusCodeError: 400 - "{\"details\":\"Couldn't find 'visualization.json' in visualization bundle.\",\"error\":\"INTERNAL_ERROR\"}"`
`  - at new StatusCodeError (/usr/local/lib/node_modules/zoomdata-chart-cli/node_modules/request-promise-core/lib/errors.js:32:15)`
`  - at Request.plumbing.callback (/usr/local/lib/node_modules/zoomdata-chart-cli/node_modules/request-promise-core/lib/plumbing.js:104:33)`
`  - at Request.RP$callback [as _callback] (/usr/local/lib/node_modules/zoomdata-chart-cli/node_modules/request-promise-core/lib/plumbing.js:46:31)`
`  - at Request.self.callback (/usr/local/lib/node_modules/zoomdata-chart-cli/node_modules/request/request.js:186:22)`
`  - at Request.emit (events.js:180:13)`
`  - at Request.<anonymous> (/usr/local/lib/node_modules/zoomdata-chart-cli/node_modules/request/request.js:1163:10)`
`  - at Request.emit (events.js:180:13)`
`  - at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/zoomdata-chart-cli/node_modules/request/request.js:1085:12)`
`  - at Object.onceWrapper (events.js:272:13)`
`  - at IncomingMessage.emit (events.js:185:15)`

I am pretty sure that I have included all the documents in the .zip folder by:

  zip -r custom.zip custom
  adding: custom/ (stored 0%)
  adding: custom/visualization.json (deflated 75%)
  adding: custom/components/ (stored 0%)
  adding: custom/components/CustomRegionsMap.js (deflated 72%)
  adding: custom/components/style.css (deflated 77%)
  adding: custom/version (stored 0%)
  adding: custom/libs/ (stored 0%)
  adding: custom/libs/lodash.min.js (deflated 64%)
  adding: custom/libs/geojson-utils.js (deflated 71%)
  adding: custom/libs/test_region_level3.js (deflated 78%)
  adding: custom/libs/test_region_level2.js (deflated 71%)
  adding: custom/libs/test_region_level1.js (deflated 65%)
  adding: custom/libs/topojson.js (deflated 78%)
  adding: custom/libs/leaflet_0.7.2.js (deflated 75%)
  adding: custom/libs/leaflet-omnivore.min.js (deflated 66%)

How shall I fix the error? Thanks.

**Comment by WerlingM** [comment]
The zip file must contain visualization.json at the root.  Try running the zip command in the same folder and something like `zip -r custom.zip .`

Also, the version of Zoomdata you are targeting must be 2.6.x.  The custom visualization import checks the version number of Zoomdata against the number listed in the version.txt file.
